### PR TITLE
Expose configFile

### PR DESCRIPTION
**Pull request by gdiggs**
We need to use some of its functionality externally, so expose it in the
API.

@codeclimate/review

### CODE REVIEW

**Comment by wfleming** [comment]
Have you looked at [`cli.getConfigForFile()`](https://github.com/codeclimate/codeclimate-eslint/blob/master/bin/eslint.js#L19)? Right now we're just using it to get the parser for logging, but you should be able to use that to get just about whatever you need.

**Comment by gdiggs** [comment]
@wfleming that does way more work than (and doesn't return the same thing as) what I need. I'm trying to get at the body of [this function](https://github.com/codeclimate/eslint/blob/master/lib/config/config-file.js#L431-L443)

**Comment by wfleming** [comment]
Oh well. Carry on then. The almost-ready latest eslint release is going to cause a lot merge conflicts with our patches, so I was hoping to avoid further patches if we could avoid it. :crying_cat_face:

**Comment by gdiggs** [comment]
Damn. This should be a very easy one to re-apply, and I think importing rather than rewriting/copying is good. Do you think it would be better to copy the logic of that into our engine?

**Comment by wfleming** [comment]
> Do you think it would be better to copy the logic of that into our engine?

Not really. We're already going to have a fair amount of manual merging to do, so I guess this won't make it much worse.

If at all possible, I do think we should add a spec in the engine for whatever functionality this is being used for: at least then it'll make verifying the eventual merge a bit easier.

What is the functionality we're implementing, though, out of curiosity? Why do we need to know which top-level config file is being used?

**Comment by gdiggs** [comment]
@wfleming one step ahead of you re: tests :)

ESLint's behavior is to not run _anything_ in the case that a configuration file doesn't exist. We want to fail hard in that scenario, rather than silently emitting no issues.

**Comment by wfleming** [comment]
Gotcha. Then :shipit:.

**Comment by wfleming** [comment]
Too late, but, as a last-ditch effort to avoid making our fork harder to maintain: would `cli.getConfigForFile` return `null` in these cases and would that work?

**Comment by gdiggs** [comment]
@wfleming yeah I can make that work! Will reset master without this change

**Pull request merged**
